services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:3000"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
