import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Footer } from "../widgets/footer";
import { Header } from "../widgets/header";
import "./globals.css";

const nunito = Nunito({
  variable: "--nunito-font",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunito.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
