export enum Endpoint {
  MY_COURSES = "/catalog/my",
  ALL_COURSES = "/catalog/all",
  CREATED_COURSES = "/catalog/created",
  LOGIN = "/login",
  REGISTER = "/register",
  FORGET_PASSWORD = "forget-password",
  COURSES = "/catalog/courses",
  PROFILE = "/profile",
  COURSE = `${Endpoint.COURSES}/{}`,
  MODULE = `${Endpoint.COURSE}/{}`,
  MATERIAL = `${Endpoint.MODULE}/{}`,
  TEST = `${Endpoint.MATERIAL}/{}`,
  COURSE_SETTINGS_TEACHERS = `${Endpoint.COURSES}/{}/settings/teachers`,
  COURSE_SETTINGS_STUDENTS = `${Endpoint.COURSES}/{}/settings/students`,
  COURSE_SETTINGS_APPLICATIONS = `${Endpoint.COURSES}/{}/settings/applications`,
  COURSE_SETTINGS_ABOUT = `${Endpoint.COURSES}/{}/settings/about`,
}
