export enum Endpoint {
  MY_COURSES = "/catalog/my",
  ADMINISTRATION = "/admin",
  ADMINISTRATION_TEACHERS = `${ADMINISTRATION}/teachers`,
  ADMINISTRATION_COURSES = `${ADMINISTRATION}/courses`,
  ALL_COURSES = "/catalog/all",
  CREATED_COURSES = "/catalog/created",
  LOGIN = "/login",
  REGISTER = "/register",
  FORGET_PASSWORD = "forget-password",
  COURSES = "/catalog/courses",
  PROFILE = "/profile",
  RESET_PASSWORD = `${PROFILE}/reset-password`,
  COURSE = `${COURSES}/{}`,
  MODULE = `${COURSE}/{}`,
  MATERIAL = `${MODULE}/{}`,
  TEST = `${MATERIAL}/{}`,
  COURSE_SETTINGS_TEACHERS = `${COURSES}/{}/settings/teachers`,
  COURSE_SETTINGS_STUDENTS = `${COURSES}/{}/settings/students`,
  COURSE_SETTINGS_APPLICATIONS = `${COURSES}/{}/settings/applications`,
  COURSE_SETTINGS_ABOUT = `${COURSES}/{}/settings/about`,
}
